<a href="https://colab.research.google.com/github/AACRobinson/IMLO-Assessment/blob/main/IMLO_Week_10_Practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Tutorial**

In [2]:
#Tensor - A multidimensional array/matrix, common in PyTorch

import torch
import numpy as np

### **Initialising Tensors**

In [3]:
#1. Directly from data
data1 = [[1, 2], [3, 4]]
data2 = [[1.0], [2.0], [3.0], [4.0]]
tensorData1 = torch.tensor(data1)
tensorData2 = torch.tensor(data2)
print(tensorData1, tensorData1.dtype)
print(tensorData2, tensorData2.dtype)

#2. From (an to) NumPy arrays
np_array1 = np.array(data1)
tensorNp1 = torch.from_numpy(np_array1)
np_array2 = tensorNp1.numpy()
print(tensorNp1)
print(np_array2)

#3. From another tensor
tensorOf1s = torch.ones_like(tensorData2) #Same dimensions and datatype as tensorData2
print(tensorOf1s)
tensorOf0s = torch.zeros((3, 3)) #Dimensions of (3, 3)
print(tensorOf0s)
tensorRandom = torch.rand_like(tensorData1, dtype=torch.float) #Same dimensions as tensorData1, but float datatype
print(tensorRandom)

tensor([[1, 2],
        [3, 4]]) torch.int64
tensor([[1.],
        [2.],
        [3.],
        [4.]]) torch.float32
tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]
tensor([[1.],
        [1.],
        [1.],
        [1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.7750, 0.3789],
        [0.2682, 0.4352]])


### **Tensor Operations**

In [38]:
#Can run these operations on a GPU - Allocate  GPU to run on with Runtime > Change Runtime Type > GPU

#Move a tensor to the GPU
if torch.cuda.is_available():
  tensorData1 = tensorData1.to('cuda')
  tensorData2 = tensorData2.to('cuda')
  #To prevent errors between tensors due to operations with them being on the cpu/cuda, will move them off
  tensorData1 = tensorData1.to('cpu')
  tensorData2 = tensorData2.to('cpu')


#Tensor slicing - identical to NumPy
tensor4x4 = torch.zeros(4, 4)
tensor4x4[1] = 1
tensor4x4[:, 2] = 1
print(tensor4x4)
print("Row 0", tensor4x4[0])
print("Column 0", tensor4x4[:, 0])
print("Row n", tensor4x4[-1])
print("Column n", tensor4x4[..., -1], "\n")


#Tensor type conversion
print(tensor4x4, tensor4x4.dtype)
tensor4x4 = tensor4x4.to(int)
print(tensor4x4, tensor4x4.dtype, "\n")


#Tensor concatenation
tensor4x8 = torch.cat([tensor4x4, tensor4x4]) #dim=0
tensor8x4 = torch.cat([tensor4x4, tensor4x4], dim=1)
print(tensor4x8)
print(tensor8x4, "\n")


#Tensor arithmetic - identical to NumPy
tensorMul2_2 = tensorData2 @ tensorData2.T
tensorMul1_1 = tensorData1.to(float).matmul(tensorData1.to(float))
tensorMul2_4x4 = torch.rand_like(tensorData2)
torch.mul(tensorData2, tensor4x4, out=tensorMul2_4x4)
print(tensorMul2_2)
print(tensorMul1_1)
print(tensorMul2_4x4, "\n")


#Get the sum of all values in a tensor (and convert to corresponding datatype)
sumOfMul2_4x4 = tensorMul2_4x4.sum()
sumOfMul2_4x4Object = sumOfMul2_4x4.item()
print(sumOfMul2_4x4Object, type(sumOfMul2_4x4Object), "\n")


#Add a scalar to all values in the tensor
tensor4x4.add_(2)
print(tensor4x4)

tensor([[0., 0., 1., 0.],
        [1., 1., 1., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]])
Row 0 tensor([0., 0., 1., 0.])
Column 0 tensor([0., 1., 0., 0.])
Row n tensor([0., 0., 1., 0.])
Column n tensor([0., 1., 0., 0.]) 

tensor([[0., 0., 1., 0.],
        [1., 1., 1., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]]) torch.float32
tensor([[0, 0, 1, 0],
        [1, 1, 1, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 0]]) torch.int64 

tensor([[0, 0, 1, 0],
        [1, 1, 1, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [0, 0, 1, 0],
        [1, 1, 1, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 0]])
tensor([[0, 0, 1, 0, 0, 0, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 1, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 0, 1, 0]]) 

tensor([[ 1.,  2.,  3.,  4.],
        [ 2.,  4.,  6.,  8.],
        [ 3.,  6.,  9., 12.],
        [ 4.,  8., 12., 16.]])
tensor([[ 7., 10.],
        [15., 22.]], dtype=torch.float64)
tensor([[0., 0., 1., 0.],
        [2., 2.,

<ipython-input-38-b84d525d089f>:42: UserWarning: An output with one or more elements was resized since it had shape [4, 1], which does not match the required output shape [4, 4]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  torch.mul(tensorData2, tensor4x4, out=tensorMul2_4x4)


### **NumPy Bridging**

In [45]:
#Tensors on the CPU can share memory locations with NumPy arrays - so data can be shared between them

tensorBridge = torch.ones(5)
numpyBridge = tensorBridge.numpy()
print("Tensor: ", tensorBridge, "\n", "NumPy: ", numpyBridge, "\n")

tensorBridge.add_(1)
print("Tensor: ", tensorBridge, "\n", "NumPy: ", numpyBridge, "\n")

np.add(numpyBridge, 1, out=numpyBridge)
print("Tensor: ", tensorBridge, "\n", "NumPy: ", numpyBridge, "\n")

Tensor:  tensor([1., 1., 1., 1., 1.]) 
 NumPy:  [1. 1. 1. 1. 1.] 

Tensor:  tensor([2., 2., 2., 2., 2.]) 
 NumPy:  [2. 2. 2. 2. 2.] 

Tensor:  tensor([3., 3., 3., 3., 3.]) 
 NumPy:  [3. 3. 3. 3. 3.] 

