In [ ]:
#This is my notes on the example that was used in the week 9 lecture.
#This Google Collab file is linked with my GitHub. It is unrelated to the project but is useful
#to refer back to to get some frame of reference when developing my project.

# **Preprocessing the Iris Dataset**

In [2]:
import pandas as pd
from sklearn import datasets

#Load the iris dataset from sklearn (we'll use a similar one in the assessment)
#Contains basic information about a bunch of flowers
iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
print(df.head())
print(df.tail())


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8


In [5]:
#Target is the our data labels, i.e. training data - we set it to float data type of later learning algorithms
#The values 0-2 indicate the three types of flower in the dataset
df["target"] = iris.target
df["target"] = df["target"].astype(float)
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  

In [6]:
#Now we are going to preprocess the data
x = df.drop("target", axis=1).values  #Dataset
y = df["target"].values   #Labels
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

# **Neural Networks**

In [7]:
#Time to start building the neural network - import PyTorch
import torch
import torch.nn as nn
import torch.nn.functional as F   #This contains useful stuff like the loss and activation functions

In [ ]:
class My_NN(nn.Module): #PyTorch neural network module - defines the class as a neural network
  def __init__(self, in_feature, hidden_layers, out_features, activation_function = F.relu)   #in_feature - number of input features (in this case 4, sepal and petal width/length)
                                                                                              #hidden_layers - list of integers, indicates the number of neurones on each layer
                                                                                              #out_features - number of output features (in this case 1, a float of value 0-2)
                                                                                              #activation_function - we're using relu to train the model (over sigmoid/step)
    super().__init__()
    if len(hidden_layers) < 1:
      raise Exception("A My_NN must have at least 1 hiddel layer")  #(Because it does)
    #Now let's add neurones by layer
    self.layers = []
    self.layers.append(nn.Linear(in_features, hidden_layers[0]))  #Takes a number of input features defined earlier, produces a number of outputs (equal to whatever is in the first element of hidden_layers)
    self.add_module("input_layer", self.layers[0]) #We name this first layer as the input layer
    for i in range(1, len(hidden_layers)-1) :
      self.layers.append(nn.Linear(hidden_layers[i-1], hidden_layers[i])) #Repeat for all layers - #input features = number of output features of last layer
      self.add_module("hidden_layer_" + str(self.layers[i]), self.layer[1]) #All intermediary layers are named hidden layers
    self.layers.append(nn.Linear(hidden_layers[len(hidden_layers-1)], out_features))  #Add the last layer - produces a number of output equal to whatever was defined earlier
    self.add_module("output_layer", self.layer[len(self.layers-1)]) #The last layer is named the output layer

    #We can get the output layer instead of the entire neural network
    self.out = self.layers[len(self.layers)-1]
    self.activation_function = activation_function

  def forward(self, x): #Feed Forward Network - Forwards the output values to the next layer
    for i in range(len(self.layers)):
